#include <inttypes.h>
#include <stdint.h>
#include <stdio.h>

typedef unsigned int uint;
typedef uint64_t u64;

extern u64 GetGX2SurfaceOffset(
    uint x, uint y, uint bpp, uint width, uint height,
    uint tile_mode, uint pitch, uint swizzle);

typedef struct Vector {
    uint mode, bpp, pitch, x, y, pipe_swizzle, bank_swizzle;
    u64 expected;
} Vector;

int main(void)
{
    // Values generated by aboood40091/GTX-Extractor addrlib.py's
    // computeSurfaceAddrFromCoordMacroTiled(), independently of this C port.
    static const Vector vectors[] = {
        { 4,  32,  64, 17, 19, 1, 2,   5460 },
        { 5,  32,  64, 17, 19, 1, 2,   3412 },
        { 6,  32,  64, 63, 31, 1, 3,  15868 },
        { 7,  16,  64, 63, 31, 1, 3,  13694 },
        { 8,   8, 256,129, 65, 0, 1,  18961 },
        { 9,  64, 256,129, 65, 0, 1, 164888 },
        {10, 128, 256, 17, 19, 1, 2,  20272 },
        {11,  32, 256, 63, 31, 1, 3,  75260 },
    };

    int failed = 0;
    for (uint i = 0; i < sizeof(vectors)/sizeof(*vectors); i++) {
        const Vector *v = vectors+i;
        const uint swizzle = v->pipe_swizzle<<8 | v->bank_swizzle<<9;
        const u64 got = GetGX2SurfaceOffset(
            v->x,v->y,v->bpp,512,128,v->mode,v->pitch,swizzle);
        if (got != v->expected) {
            fprintf(stderr,"mode %u bpp %u: got %" PRIu64 ", expected %" PRIu64 "\n",
                v->mode,v->bpp,got,v->expected);
            failed = 1;
        }
    }
    return failed;
}
