#include "wszst_cmd/headers.inc"
#include "wszst_cmd/test_inspect.inc"
#include "wszst_cmd/features_diff.inc"
#include "wszst_cmd/compress.inc"
#include "wszst_cmd/create_update.inc"
#include "wszst_cmd/formats.inc"
#include "wszst_cmd/main.inc"
