///////////////////////////////////////////////////////////////////////////////
////////////////////////////////   draw data   ////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

const s16 DbFileDraw[175] = {
	// 0: empty list at index 0
	0,

	// 1: castletree1.brres
	8,
	DFD_TREE,
	370,
	20,
	920,
	1820,
	300,
	900,
	0,

	// 10: castletree2.brres
	8,
	DFD_TREE,
	370,
	0,
	920,
	1820,
	300,
	900,
	0,

	// 19: coin.brres
	2,
	DFD_COIN,
	0,

	// 22: DKtreeA64.brres
	8,
	DFD_TREE,
	240,
	0,
	1300,
	2000,
	300,
	700,
	0,

	// 31: DKtreeB64.brres
	8,
	DFD_TREE,
	190,
	0,
	1600,
	1190,
	300,
	280,
	0,

	// 40: DKturibashiGC.brres
	8,
	DFD_RECTANGLE,
	KCL_FLAG_BRIDGE - N_KCL_FLAG,
	915,
	7250,
	-9,
	0,
	0,
	0,

	// 49: dokan_sfc.brres
	5,
	DFD_CYLINDER_Y,
	KCL_FLAG_DOKAN - N_KCL_FLAG,
	220,
	161,
	0,

	// 55: donkytree1GC.brres
	8,
	DFD_TREE,
	380,
	310,
	1300,
	2050,
	300,
	400,
	0,

	// 64: donkytree2GC.brres
	8,
	DFD_TREE,
	350,
	0,
	1100,
	1600,
	300,
	400,
	0,

	// 73: gardentreeDS.brres
	8,
	DFD_TREE,
	240,
	0,
	540,
	620,
	300,
	1800,
	0,

	// 82: HeyhoTreeGBA.brres
	8,
	DFD_TREE,
	100,
	0,
	330,
	530,
	100,
	200,
	0,

	// 91: itembox.brres
	2,
	DFD_ITEMBOX,
	0,

	// 94: karehayama.brres
	7,
	DFD_PYRAMID,
	KCL_FLAG_KAREHAYAMA - N_KCL_FLAG,
	5,
	300,
	360,
	-100,
	0,

	// 102: kinoko.brres
	2,
	DFD_KINOKO,
	0,

	// 105: mariotreeGC.brres
	8,
	DFD_TREE,
	340,
	120,
	900,
	1700,
	300,
	900,
	0,

	// 114: obakeblockSFC.brres
	4,
	DFD_CUBE,
	KCL_FLAG_OBAKEBLOCK - N_KCL_FLAG,
	250,
	0,

	// 119: pakkun_dokan.brres
	6,
	DFD_CYLINDER_Y,
	KCL_FLAG_DOKAN - N_KCL_FLAG,
	288,
	182,
	-69,
	0,

	// 126: PalmTree.brres
	8,
	DFD_TREE,
	330,
	0,
	1850,
	2200,
	300,
	1050,
	0,

	// 135: peachtreeGC.brres
	8,
	DFD_TREE,
	370,
	175,
	1250,
	2050,
	300,
	450,
	0,

	// 144: TownTreeDS.brres
	8,
	DFD_TREE,
	420,
	0,
	800,
	1620,
	300,
	1630,
	0,

	// 153: WLdokanGC.brres
	5,
	DFD_CYLINDER_Z,
	KCL_FLAG_DOKAN - N_KCL_FLAG,
	1600,
	200,
	0,

	// 159: WLscreenGC.brres
	9,
	DFD_CUBOID,
	KCL_FLAG_DECORATION - N_KCL_FLAG,
	12920,
	10906,
	3100,
	0,
	3505,
	-1550,
	0,

	// 169: woodbox.brres
	5,
	DFD_CUBE,
	KCL_FLAG_WOODBOX - N_KCL_FLAG,
	200,
	100,
	0,
};

//
///////////////////////////////////////////////////////////////////////////////
////////////////////////////////   data base   ////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

